### ISSUE TITLE
where is the training code？

### ISSUE THREAD

**Issue by realize-qzq** [neilctwu/YouyakuMan#1]
there is only evaluate code in your repo

**Comment by neilctwu** [comment]
Hi, Thanks for the notice. 
Training part of code wasn't upload before. I'll make it available before end of this week, and inform here.

**Comment by realize-qzq** [comment]
> Hi, Thanks for the notice.
> Training part of code wasn't upload before. I'll make it available before end of this week, and inform here.

Expect it!

**Comment by neilctwu** [comment]
Uploaded training part, its a little mass though. Hope it helps.

**Comment by neilctwu** [comment]
Uploaded training part, its a little mass though. Will organize it when available.
Hope it helps.
