### ISSUE TITLE
pretrained_model_file

### ISSUE THREAD

**Issue by yutozabu** [neilctwu/YouyakuMan#11]
I got Error below with `$python youyakumanJPN_train.py -data_folder [training_txt_path] -save_path [model_saving_path] -train_from YouyakuMan/checkpoint/jp/opt_step_1200000.pt`

`
Traceback (most recent call last):
  File "youyakumanJPN_train.py", line 63, in <module>
    opt = dict(checkpoint['opt'])
KeyError: 'opt'
`

How should I fix it?
If I don't specify train_from, it works.

**Comment by isseco** [comment]
Could you please tell me how you solved it?
