### ISSUE TITLE
training data format

### ISSUE THREAD

**Issue by ronswa** [neilctwu/YouyakuMan#2]
Are there any restrictions on the training data format and content?
How should I fix the "DataWarning with data has error" exception? 
P.S. Thanks and keep up the good work!

**Comment by neilctwu** [comment]
Hi ronswa,

Train data used in `youyakumanJPN_train.py`  is load from `src/models/train_dataloader.py`, which by default is binary pickle file, with dictionary object in it. Contents of dictionary is like this:
{'body': 'TEXT_BODT',
 'summary': 'SUMMARY_1<sep>SUMMARY_2<sep>SUMMARY3'}

You may want to change this part to fit your own training data. 
Also, thanks for pointing out the issue. I'll add the training data description to README and remove the restriction of pickle format ASAP.

**Comment by ronswa** [comment]
So is it safe to assume the training data is one pickle file with several dictionaries for each text? Or is it going to be multiple files each with a dictionary in it?

**Comment by ronswa** [comment]
Hi neilctwu,

Thanks for the reply. I read the train_dataloader.py script and made the train data files as you've described above. Unfortunately, the exception still occurs. In fact, even if I set the -data_folder arg as a non-existent directory, the same exception:

"DataWarning with data has error"  gets printed repeatedly. I've tried replacing the print command of the exception into "continue", and it becomes: 

LR is: 5e-05
gpu_rank 0
^CTraceback (most recent call last):
  File "youyakumanJPN_train.py", line 71, in <module>
    trainer.train(train_loader_fct, args.train_steps)
  File "/opt/share-vol/zo/YouyakuMan/src/models/trainer.py", line 49, in train
    batch = next(train_iter)
  File "/opt/share-vol/zo/YouyakuMan/src/models/train_dataloader.py", line 80, in __next__
    return self._next_batch()
  File "/opt/share-vol/zo/YouyakuMan/src/models/train_dataloader.py", line 104, in _next_batch
    for i in range(self.batch_size):

until I keyboardInterrupt. Any ideas on what's wrong or how I should proceed?

**Comment by ronswa** [comment]
Hi neilctwu! Thanks for the response.
I tried to run the training code with a tiny dataset to see if it works. I have 25 pickle files that are being loaded correctly. 
`def _next_batch(self):
        while True:
            try:
                dataset = []
                #print(self.batch_size)
                try:
                    # Drop the current dataset for decreasing memory
                    for i in range(self.batch_size):
                        rawdata = next(self.iterer)
                        data = self.preprocessor(rawdata, self.input_len)
                        dataset.append(data)
                    batched_dataset = Batch(dataset=dataset, device=self.device)
                    return batched_dataset
                except Exception as e:
                    print('DataWarning with data has error {}'.format(e))
            except StopIteration:
                self.iterer = self._lazy_loader()
                return None`

The `train_dataloader.py` does load the files but never goes past `rawdata = next(self.iterer)`. It loads 25 "rawdata" in my case and proceeds to go into `print('DataWarning with data has error {}'.format(e))` part. Is there anything I am doing wrong?

**Comment by ronswa** [comment]
Hi neilctwu, thanks for the reply. 
You may also look at `preprocess.py` as it needs a `{'name' : 'title'}` component in addition to the summary and body. Training files without 'name' invokes the `DataWarning` exception.

Quick question, how long did it take for you to acquire the cp_710000 checkpoint?

**Comment by neilctwu** [comment]
Hi ronswa,
Thanks for the feedback, really appreciate it. 
`'name'` was initially used as debugging variable, its my fail to remain it in codes. I'll remove it later.
About training time, Its been a while since training so my memory is quite ambiguous. I think is about 2-3days by single RTX2080Ti.

**Comment by neilctwu** [comment]
This issue considered finished therefore will be closed
